tags:
  eggs-1: 大战场彩蛋语音
  eggs-2: 大卫语音
  boss-1: 赛伊德/老赛
  boss-2: 雷斯/肘击王
  boss-3: 蓝鹰直升机/巴克什飞机
  boss-4: 德穆兰/老太
  boss-5-1: 渡鸦
  boss-5-2: 格赫罗斯/典狱长
  boss-501: 渡鸦随从/渡鸦跟随者/渡鸦小弟
  boss-502: 格赫罗斯随从/格赫罗斯跟随者/格赫罗斯小弟/典狱长随从/典狱长跟随者/典狱长小弟
  task-0: 契约任务/保险箱任务
  task-1: 破壁行动/破壁
  task-2: 铁穹行动/铁穹
  task-3-1: 庇护者行动/博士
  task-3-2: 局内任务
  task-4: 飞升者行动/飞升/火箭
  task-4-2: 焰火行动/焰火
  task-5: 黑潮行动/黑潮
  task-5-0: 监狱行动
  task-5-2: 猎鸦人行动
  task-5-3: 诛星者行动
  Evac-1: 撤离语音/直升机
  Evac-2: 大坝撤离语音/电梯
  Evac-3: 长弓溪谷列车撤离/火车/列车
  event-1: 曼德尔砖破译/曼德尔
  event-2: 长弓溪谷山火/山火
  event-3: 红鼠窝游戏模式/红鼠窝
  event-4: 局内任务接管/接管/relink语音
  event-4-1: relink语音
  event-5: 哈夫克保险公司/倾家荡产/哈夫克保险
  festival-0: 联动语音
  festival-1: 指挥手令活动
  festival-2: 哈夫克保险
  festival-3: 空投无线电
  bf-1: 战场部署
  bf-2: 战场就绪
  BF_GTI: GTI战场语音
  bf-load-gti: GTI过场语音
  BF_Haavk: 哈夫克战场语音
  bf-load-haavk: 哈夫克过场语音
  haavk: 哈夫克全兵种语音
  commander: 指令
  other-1: 地图选择语音/选图
  other-2: 曼德尔抽奖语音/抽奖
  skin-1: 气象感应语音
  enter-5: 监狱进图/监狱过场
  babel: 巴别塔语音/巴别塔
  Beginner: 新手教程
keywords:
  大战场彩蛋语音: eggs-1
  大卫语音: eggs-2
  赛伊德: boss-1
  老赛: boss-1
  雷斯: boss-2
  肘击王: boss-2
  蓝鹰直升机: boss-3
  巴克什飞机: boss-3
  德穆兰: boss-4
  老太: boss-4
  渡鸦: boss-5-1
  格赫罗斯: boss-5-2
  典狱长: boss-5-2
  渡鸦随从: boss-501
  渡鸦跟随者: boss-501
  渡鸦小弟: boss-501
  格赫罗斯随从: boss-502
  格赫罗斯跟随者: boss-502
  格赫罗斯小弟: boss-502
  典狱长随从: boss-502
  典狱长跟随者: boss-502
  典狱长小弟: boss-502
  契约任务: task-0
  保险箱任务: task-0
  破壁行动: task-1
  破壁: task-1
  铁穹行动: task-2
  铁穹: task-2
  庇护者行动: task-3-1
  博士: task-3-1
  局内任务: task-3-2
  飞升者行动: task-4
  飞升: task-4
  火箭: task-4
  焰火行动: task-4-2
  焰火: task-4-2
  黑潮行动: task-5
  黑潮: task-5
  监狱行动: task-5-0
  猎鸦人行动: task-5-2
  诛星者行动: task-5-3
  撤离语音: Evac-1
  直升机: Evac-1
  大坝撤离语音: Evac-2
  电梯: Evac-2
  长弓溪谷列车撤离: Evac-3
  火车: Evac-3
  列车: Evac-3
  曼德尔砖破译: event-1
  曼德尔: event-1
  长弓溪谷山火: event-2
  山火: event-2
  红鼠窝游戏模式: event-3
  红鼠窝: event-3
  局内任务接管: event-4
  接管: event-4
  relink语音: event-4-1
  哈夫克保险公司: event-5
  倾家荡产: event-5
  哈夫克保险: festival-2
  联动语音: festival-0
  指挥手令活动: festival-1
  空投无线电: festival-3
  战场部署: bf-1
  战场就绪: bf-2
  GTI战场语音: BF_GTI
  GTI过场语音: bf-load-gti
  哈夫克战场语音: BF_Haavk
  哈夫克过场语音: bf-load-haavk
  哈夫克全兵种语音: haavk
  指令: commander
  地图选择语音: other-1
  选图: other-1
  曼德尔抽奖语音: other-2
  抽奖: other-2
  气象感应语音: skin-1
  监狱进图: enter-5
  监狱过场: enter-5
  巴别塔语音: babel
  巴别塔: babel
  新手教程: Beginner
characters:
  蜂医: Voice_101
  蛊: Voice_102
  蛊A: Voice_102_SkinA
  露娜: Voice_201
  露娜A: Voice_201_SkinA
  骇爪: Voice_202
  骇爪A: Voice_202_SkinA
  骇爪B: Voice_202_SkinB
  银翼: Voice_203
  红狼: Voice_301
  红狼A: Voice_301_SkinA
  红狼B: Voice_301_SkinB
  威龙: Voice_302
  威龙A: Voice_302_SkinA
  无名: Voice_303
  疾风: Voice_304
  深蓝: Voice_401
  乌鲁鲁: Voice_402
  牧羊人: Voice_403
categories:
  Amb: Amb
  环境音效: Amb
  amb: Amb
  CutScene: CutScene
  过场动画: CutScene
  cutscene: CutScene
  Festivel: Festivel
  节日活动: Festivel
  festivel: Festivel
  Intro: Intro
  介绍: Intro
  intro: Intro
  Music: Music
  背景音乐: Music
  music: Music
  UI: UI
  界面: UI
  ui: UI
  Voice: Voice
  角色语音: Voice
  voice: Voice
  Voice_SOL_MS: Voice_SOL_MS
  单人模式: Voice_SOL_MS
  voice_sol_ms: Voice_SOL_MS
