"33": 烬区-攻防
"34": 烬区-占领
"54": 攀升-攻防
"75": 临界点-攻防
"103": 攀升-占领
"107": 沟壕战-攻防
"108": 沟壕战-占领
"111": 断轨-攻防
"112": 断轨-占领
"113": 贯穿-攻防
"114": 贯穿-占领
"117": 攀升-钢铁洪流
"118": 烬区-围攻
"119": 烬区-钢铁洪流
"121": 刀锋-攻防
"122": 刀锋-占领
"128": 沟壕战-围攻
"138": 金字塔-攻防
"139": 金字塔-占领
"151": 断层-攻防
"152": 断层-占领
"210": 临界点-占领
"227": 沟壕战-钢铁洪流
"302": 风暴眼-攻防
"303": 风暴眼-占领
"514": 刀锋-团队死斗
"516": 沟壕战-霰弹风暴
"517": 攀升-霰弹风暴
"526": 断轨-钢铁洪流
"603": 临界点-胜者为王
"606": 断轨-胜者为王
"901": 攀升-团队死斗
"902": 沟壕战-团队死斗
"903": 烬区-团队死斗
"904": 断轨-团队死斗
"1901": 长弓溪谷-常规
"1902": 长弓溪谷-机密
"1912": 长弓溪谷-机密（单排）
"2201": 零号大坝-常规
"2202": 零号大坝-机密
"2212": 零号大坝-机密（单排）
"2231": 零号大坝-前夜
"2232": 零号大坝-永夜
"2233": 零号大坝-终夜
"2242": 零号大坝-水淹
"3901": 航天基地-机密
"3902": 航天基地-绝密
"8102": 巴克什-机密
"8103": 巴克什-绝密
"8803": 潮汐监狱-绝密
