sol:
  "1000": 青铜 III
  "1150": 青铜 II
  "1300": 青铜 I
  "1450": 白银 III
  "1600": 白银 II
  "1750": 白银 I
  "1900": 黄金 IV
  "2100": 黄金 III
  "2300": 黄金 II
  "2500": 黄金 I
  "2700": 铂金 IV
  "2900": 铂金 III
  "3100": 铂金 II
  "3300": 铂金 I
  "3500": 钻石 V
  "3750": 钻石 IV
  "4000": 钻石 III
  "4250": 钻石 II
  "4500": 钻石 I
  "4750": 黑鹰 V
  "5000": 黑鹰 IV
  "5250": 黑鹰 III
  "5500": 黑鹰 II
  "5750": 黑鹰 I
  "6000": 三角洲巅峰
tdm:
  "0": 列兵 III
  "150": 列兵 II
  "300": 列兵 I
  "450": 上等兵 III
  "600": 上等兵 II
  "750": 上等兵 I
  "900": 军士长 IV
  "1100": 军士长 III
  "1300": 军士长 II
  "1500": 军士长 I
  "1700": 尉官 IV
  "1900": 尉官 III
  "2100": 尉官 II
  "2300": 尉官 I
  "2500": 校官 V
  "2750": 校官 IV
  "3000": 校官 III
  "3250": 校官 II
  "3500": 校官 I
  "3750": 将军 V
  "4000": 将军 IV
  "4250": 将军 III
  "4500": 将军 II
  "4750": 将军 I
  "5000": 统帅
